### PR TITLE
If Access-Control-Request-Headers is specified in request, copy it to Access-Control-Response-Headers in response

### PR DESCRIPTION
**Pull request by sangkeon**
If Access-Control-Request-Headers is specified in request, copy it to Access-Control-Response-Headers in response

### CODE REVIEW

**Comment by mohsen1** [comment]
Browsers are usually making a "preflight" OPTIONS call to get `Access-Control-Headers` and other access control headers. It's not the same request usually that expects the headers.

**Comment by sangkeon** [comment]
You right. I tested it again.
In Firefox,  Access-Control-Headers in a "preflight" OPTIONS call and following request is same.
In Chrome, Access-Control-Headers is not set in a "preflight" OPTIONS call and Access-Control-Headers is  only set in following flight request.

If OPTIONS request is excluded, isn't it safe to copy Access-Control-Request-Headers to Access-Control-Response-Headers?

**Comment by mohsen1** [comment]
HTTP and REST specifically should be stateless. You should not make requests that have side effects on other requests

**Comment by sangkeon** [comment]
Sorry, my test is wrong.
Chrome and Firefox works the same in preflight.
And I cannot gurantee it is always safe to copy Access-Control-Request-Headers to Access-Control-Response-Headers

Drop this request please.

**Pull request closed without merging**
